<a href="https://colab.research.google.com/github/sakibreza/My-PyTorch-Playground/blob/master/Autograd_with_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd with tensors

In [1]:
import torch

In [2]:
w = torch.randn(4, 3, requires_grad = True)

In [3]:
w

tensor([[-0.8255, -1.2068,  1.6042],
        [-0.1605,  0.3815,  0.5431],
        [ 0.5294, -1.1304, -0.8249],
        [ 0.6918, -1.3935,  0.1303]], requires_grad=True)

In [5]:
w.requires_grad_(False)

tensor([[-0.8255, -1.2068,  1.6042],
        [-0.1605,  0.3815,  0.5431],
        [ 0.5294, -1.1304, -0.8249],
        [ 0.6918, -1.3935,  0.1303]])

In [6]:
w.requires_grad_(True)

tensor([[-0.8255, -1.2068,  1.6042],
        [-0.1605,  0.3815,  0.5431],
        [ 0.5294, -1.1304, -0.8249],
        [ 0.6918, -1.3935,  0.1303]], requires_grad=True)

In [7]:
y = torch.exp(w)
y

tensor([[0.4380, 0.2992, 4.9741],
        [0.8518, 1.4644, 1.7214],
        [1.6980, 0.3229, 0.4383],
        [1.9974, 0.2482, 1.1391]], grad_fn=<ExpBackward>)

In [8]:
y.grad_fn

In [10]:
out = y.mean()
out

tensor(1.2994, grad_fn=<MeanBackward0>)

In [13]:
print(w.grad)

None


In [14]:
out.backward()

In [15]:
print(w.grad)

tensor([[0.0365, 0.0249, 0.4145],
        [0.0710, 0.1220, 0.1434],
        [0.1415, 0.0269, 0.0365],
        [0.1664, 0.0207, 0.0949]])


In [16]:
w.detach()

tensor([[-0.8255, -1.2068,  1.6042],
        [-0.1605,  0.3815,  0.5431],
        [ 0.5294, -1.1304, -0.8249],
        [ 0.6918, -1.3935,  0.1303]])

In [17]:
print(out.requires_grad)

with torch.no_grad():
  out = (w + y).mean()

print(out.requires_grad)

True
False
