<a href="https://colab.research.google.com/github/sakibreza/My-PyTorch-Playground/blob/master/Tensors_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors 

In [1]:
import torch

## zeros()

In [2]:
w = torch.zeros(4, 3)
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [3]:
w.size()

torch.Size([4, 3])

In [4]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In [5]:
w = torch.rand(4, 3)
w

tensor([[0.0435, 0.5008, 0.1292],
        [0.9203, 0.2716, 0.2130],
        [0.4544, 0.5776, 0.4642],
        [0.1527, 0.0887, 0.9311]])

In [6]:
t = torch.rand_like(w)
t

tensor([[7.3367e-04, 1.2123e-01, 9.3615e-01],
        [4.2216e-01, 5.2992e-01, 4.8243e-01],
        [6.3244e-02, 3.9024e-01, 3.5982e-01],
        [8.3868e-02, 5.2678e-01, 9.8966e-01]])

## fill_()

In [7]:
w.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [8]:
w

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
t = w.view(3, 4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
w.view(6, -1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

## numpy()

In [12]:
t = w.numpy()
t

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [13]:
type(t)

numpy.ndarray